version: 2
updates:
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: weekly
    groups:
      kotlin-build:
        patterns:
          - "org.jetbrains.kotlin*"
          - "org.jetbrains.compose*"
          - "com.google.devtools.ksp*"
      ktor:
        patterns:
          - "io.ktor*"
      androidx:
        patterns:
          - "androidx*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - "*"
